In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [6]:
dir(os)

['DirEntry',
 'EX_OK',
 'F_OK',
 'GenericAlias',
 'Mapping',
 'MutableMapping',
 'O_APPEND',
 'O_BINARY',
 'O_CREAT',
 'O_EXCL',
 'O_NOINHERIT',
 'O_RANDOM',
 'O_RDONLY',
 'O_RDWR',
 'O_SEQUENTIAL',
 'O_SHORT_LIVED',
 'O_TEMPORARY',
 'O_TEXT',
 'O_TRUNC',
 'O_WRONLY',
 'P_DETACH',
 'P_NOWAIT',
 'P_NOWAITO',
 'P_OVERLAY',
 'P_WAIT',
 'PathLike',
 'R_OK',
 'SEEK_CUR',
 'SEEK_END',
 'SEEK_SET',
 'TMP_MAX',
 'W_OK',
 'X_OK',
 '_AddedDllDirectory',
 '_Environ',
 '__all__',
 '__builtins__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_check_methods',
 '_execvpe',
 '_exists',
 '_exit',
 '_fspath',
 '_get_exports_list',
 '_walk',
 '_wrap_close',
 'abc',
 'abort',
 'access',
 'add_dll_directory',
 'altsep',
 'chdir',
 'chmod',
 'close',
 'closerange',
 'cpu_count',
 'curdir',
 'defpath',
 'device_encoding',
 'devnull',
 'dup',
 'dup2',
 'environ',
 'error',
 'execl',
 'execle',
 'execlp',
 'execlpe',
 'execv',
 'execve',
 'execvp',
 'execvpe',
 'extsep',
 'fdopen',
 'fsdecode',
 'fsencode',
 'fspath',
 'fstat',
 'fsync',
 'ftruncate',
 'get_exec_path',
 'get_handle_inheritable',
 'get_inheritable',
 'get_terminal_size',
 'getcwd',
 'getcwdb',
 'getenv',
 'getlogin',
 'getpid',
 'getppid',
 'isatty',
 'kill',
 'linesep',
 'link',
 'listdir',
 'lseek',
 'lstat',
 'makedirs',
 'mkdir',
 'name',
 'open',
 'pardir',
 'path',
 'pathsep',
 'pipe',
 'popen',
 'putenv',
 'read',
 'readlink',
 'remove',
 'removedirs',
 'rename',
 'renames',
 'replace',
 'rmdir',
 'scandir',
 'sep',
 'set_handle_inheritable',
 'set_inheritable',
 'spawnl',
 'spawnle',
 'spawnv',
 'spawnve',
 'st',
 'startfile',
 'stat',
 'stat_result',
 'statvfs_result',
 'strerror',
 'supports_bytes_environ',
 'supports_dir_fd',
 'supports_effective_ids',
 'supports_fd',
 'supports_follow_symlinks',
 'symlink',
 'sys',
 'system',
 'terminal_size',
 'times',
 'times_result',
 'truncate',
 'umask',
 'uname_result',
 'unlink',
 'unsetenv',
 'urandom',
 'utime',
 'waitpid',
 'waitstatus_to_exitcode',
 'walk',
 'write']

In [7]:
os.getcwd()

'C:\\Users\\SUDHARSHAN'

In [10]:
os.chdir("F:\TopMentor_DataScience\Batch 103 Day 31")
os.getcwd()

'F:\\TopMentor_DataScience\\Batch 103 Day 31'

In [43]:
df1=pd.read_excel("Data Preprocessing Data File.xlsx")

df1

   Country   Age   Salary  Purchased
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes

In [68]:
df1.iloc[:,1:2]

   Age
0  44.0
1  27.0
2   NaN
3  39.0
4   NaN
5  35.0
6  39.0
7  48.0
8  50.0
9  37.0

In [65]:
df1.fillna(df1.mode.iloc[:,0:1])

AttributeError: 'function' object has no attribute 'iloc'

KeyError: 'Country'